<?php

/**
 * @file
 * Main file for hooks and custom functions.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\Request;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function contact_tools_form_contact_message_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_state->get(['contact_tools', 'is_ajax'])) {
    $class_name = Html::getClass("{$form_id}-contact-tools-processed");
    $form['#attributes']['class'][] = $class_name;

    // System with errors, alerts and status messages.
    $form['system_messages'] = [
      '#type' => 'status_messages',
      '#weight' => -100,
    ];

    $form['actions']['submit']['#ajax'] = [
      'callback' => 'contact_tools_ajax_submit_handler',
      'event' => 'click',
      'progress' => [
        'type' => 'throbber',
      ],
    ];
  }
}

/**
 * Ajax submit handler for contact form called with AJAX support.
 */
function contact_tools_ajax_submit_handler(array &$form, FormStateInterface $form_state, Request $request) {
  $form_state->setRebuild();
  $contact_form_bundle = $form_state->getFormObject()->getEntity()->bundle();

  $class_name = '.' . Html::getClass($form['#form_id'] . '-contact-tools-processed');

  $ajax_response = new AjaxResponse();
  // This command fix focus jumps on the page is there is multiple forms.
  // @see /core/misc/ajax.js:861-884
  $ajax_response->addCommand(new InvokeCommand($class_name, 'focus'));
  $ajax_response->addCommand(new ReplaceCommand($class_name, $form));

  $hook_alters = [
    'contact_tools_ajax_response',
    'contact_tools_' . $contact_form_bundle . '_ajax_response',
  ];
  \Drupal::moduleHandler()
    ->alter($hook_alters, $ajax_response, $form, $form_state);
  return $ajax_response;
}

/**
 * Implements hook_robotstxt().
 *
 * Exclude AJAX routes for search spiders.
 */
function contact_tools_robotstxt() {
  return [
    'Disallow: /contact-tools',
  ];
}
