<?php

/**
 * @file
 * Main file for hooks and custom functions.
 */
use Drupal\Component\Utility\Html;

/**
 * Implements hook_form_alter().
 */
function contact_tools_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $storage = $form_state->getStorage();

  if (isset($storage['contact_tools'])) {
    if ($storage['contact_tools']['is_ajax']) {
      // @TODO rewrite code to update entire form.
      //$message_wrapper_id = Html::getUniqueId($form['#form_id'] . '-system-messages');

      $form['system_messages'] = [
        '#type' => 'item',
        '#markup' => '',
        '#id' => Html::getClass($form['#form_id']) . '-system-messages',
        '#weight' => -100,
      ];
      $form['actions']['submit']['#ajax'] = [
        'callback' => 'Drupal\contact_tools\Controller\ContactToolsAjaxController::ajaxSubmitHandler',
        'event' => 'click',
        'progress' => [
          'type' => 'throbber',
        ],
      ];
    }
  }
}